python -u run.py \
  --is_training 1 \
  --root_path ./dataset/ \
  --data_path /home/tupham/Downloads/updated_traffic_data_formatted.csv \
  --model FEDformer \
  --batch_size 8 \
  --train_epochs 5 \
  --patience 2 \
  --freq='t' \
  --detail_freq='t' \
  --seq_len 96 \
  --label_len 48 \
  --pred_len=96 \
  --features S \
  --target Vehicles \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 1 \
  --dec_in 1 \
  --c_out 1 \
  --d_model 512 \
  --itr 2 \
  --do_predict